spring:
  datasource:
    url: jdbc:h2:mem:recepcao-igreja
    username: sa
    password: password
    driverClassName: org.h2.Driver
  sql.init.mode: always
  jackson:
    serialization:
      fail-on-empty-beans: false
  
  jpa:
    hibernate:
      ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true